# Generated by Django 5.2.4 on 2025-07-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='user',
        ),
        migrations.AlterField(
            model_name='model',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='stage_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
