# Generated by Django 5.2.4 on 2025-07-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_remove_model_user_alter_model_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='email',
        ),
    ]
