# Generated by Django 5.2.4 on 2025-08-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_remove_model_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name*')),
                ('phone', models.CharField(max_length=20, verbose_name='Mobile Number*')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail*')),
                ('city', models.CharField(max_length=100, verbose_name='City*')),
                ('country', models.CharField(max_length=100, verbose_name='Country*')),
                ('age', models.PositiveIntegerField(verbose_name='Age*')),
                ('height', models.CharField(max_length=30, verbose_name='Height*')),
                ('other_agency', models.CharField(blank=True, max_length=100, verbose_name='Other Agencies')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram (username)')),
                ('photo1', models.ImageField(upload_to='model_photos/', verbose_name='Photo #1*')),
                ('photo2', models.ImageField(upload_to='model_photos/', verbose_name='Photo #2*')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='model_photos/', verbose_name='Photo #3 (optional)')),
                ('data_policy', models.BooleanField(default=False, verbose_name='Privacy Policy*')),
            ],
        ),
    ]
