# Generated by Django 5.2.4 on 2025-08-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_modelapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelapplication',
            name='other_agency',
        ),
        migrations.AddField(
            model_name='modelapplication',
            name='bust_chest',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bust / Chest*'),
        ),
        migrations.AddField(
            model_name='modelapplication',
            name='hips',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Hips*'),
        ),
        migrations.AddField(
            model_name='modelapplication',
            name='shoe',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Shoe*'),
        ),
        migrations.AddField(
            model_name='modelapplication',
            name='waist',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Waist*'),
        ),
    ]
