# Generated by Django 5.2.4 on 2025-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_alter_blog_options_blog_image_blog_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('course_type', models.CharField(choices=[('essence', 'NTA ESSENCE'), ('vision', 'NTA VISION'), ('couture', 'NTA COUTURE'), ('connect', 'NTA CONNECT')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Registration',
                'verbose_name_plural': 'Course Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
