# Generated by Django 5.2.4 on 2025-08-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='models/slideshow/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in slideshow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow_images', to='one.model')),
            ],
            options={
                'verbose_name': 'Model Image',
                'verbose_name_plural': 'Model Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
