# Generated by Django 5.2.4 on 2025-08-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_modelimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='stage_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='address',
        ),
        migrations.RemoveField(
            model_name='model',
            name='bust_waist_hip',
        ),
        migrations.RemoveField(
            model_name='model',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='model',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='model',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='model',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='model',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='weight',
        ),
        migrations.AddField(
            model_name='model',
            name='chest_bust',
            field=models.DecimalField(choices=[('C', 'Chest'), ('B', 'Bust')], decimal_places=1, default=1, help_text='Chest/Bust in cm', max_digits=4),
        ),
        migrations.AddField(
            model_name='model',
            name='hips',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Hips in cm', max_digits=4),
        ),
        migrations.AddField(
            model_name='model',
            name='waist',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
