# Generated by Django 5.2.4 on 2025-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0012_rename_stage_name_model_name_remove_model_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='chest_bust',
        ),
        migrations.AddField(
            model_name='model',
            name='chest_bust_size',
            field=models.DecimalField(decimal_places=1, default=90.0, help_text='Chest/Bust measurement in cm', max_digits=4),
        ),
        migrations.AddField(
            model_name='model',
            name='chest_bust_type',
            field=models.CharField(choices=[('C', 'Chest'), ('B', 'Bust')], default='C', help_text='Chest or Bust', max_length=1),
        ),
        migrations.AlterField(
            model_name='model',
            name='hips',
            field=models.DecimalField(decimal_places=1, default=95.0, help_text='Hips in cm', max_digits=4),
        ),
        migrations.AlterField(
            model_name='model',
            name='shoe_size',
            field=models.CharField(default='7', max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='waist',
            field=models.DecimalField(decimal_places=1, default=75.0, help_text='Waist in cm', max_digits=4),
        ),
    ]
