# Generated by Django 5.1.1 on 2025-08-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0014_alter_blog_options_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('photoshoot', 'Photoshoot'), ('runway', 'Runway Show'), ('commercial', 'Commercial'), ('event', 'Event'), ('campaigns', 'Campaigns'), ('ugc_influencer', 'UGC & Influencer Content')], max_length=20),
        ),
    ]
