# Generated by Django 5.1.1 on 2025-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0017_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
