# Generated by Django 5.1.1 on 2025-09-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0018_courseregistration_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='state',
        ),
    ]
